### ISSUE TITLE
Spiel schließt beim Aktivieren der Kamera mit Y

### ISSUE THREAD

**Issue by Joshua-Ziener** [4c65736975/cameraSystem#34]
### Version

1.0.0.1

### Game Version

Farming Simulator 22 (1.13.1.1)

### 👣 Steps to reproduce

[log.txt](https://github.com/4c65736975/cameraSystem/files/14072095/log.txt)

### ⛔️ Actual Behavior

Spiel schließt beim Aktivieren der Kamera mit Y

**Comment by 4c65736975** [comment]
Can you check on a clean savegame with only this modification?

**Comment by Joshua-Ziener** [comment]
I removed all mods, but it still closes the game.

**Comment by 4c65736975** [comment]
It's hard for me to say what could be the reason, I can't reproduce this problem, everything works fine, you are also the only person reporting such a problem. Did the modification work before? Or not from the very beginning?

**Comment by Basti06** [comment]
Hab aber auch das Problem,werde nachher aber nochmal schauen an welchem Mod es vllt liegt

**Comment by Joshua-Ziener** [comment]
Habe alle Mods entfernt und auch die Taste geändert und sobald ich die Kamera anschalten möchte, schließt er das Spiel.

**Comment by 4c65736975** [comment]
Okay, I just tested the modifications with the latest version of the game and in fact, after updating to version (1.13.1.1), after turning on the camera, the game turns off. I'm afraid that it may not be repairable on my part and Giants Software made some mistake in the update, but the problem jumps to the first place and I will try to fix it, if it is not possible, I will try to contact Giants Software. Thank you for reporting, the issue will be closed automatically once the bug is fixed.

**Comment by Basti06** [comment]
Welche map habt ihr ausprobiert bis jetzt?
spielversion und welche dlc´s mit version genommen?

Also mit folgenden dlc´s und den Versionen gibt es keine probleme. da ich jetzt aber gerade am Laptop bin weis ich nicht welche Versionen ich am PC benutze
Map: Elmcreek
Spielversio:1.13.1.1
AGI Pack 1.1.0.0
Claas Xerion Saddle trac pack 1.1.0.0
Göweil pack 1.1.0.0
Horsch agrovation pack 1.2.0.0
Hay & Forage pack 1.0.0.0
OXBO pack 1.0.0.0
Premium Expansion 1.1.0.0
Pumps N´ Hoses pack 1.3.1.0
